import profile from "../../assets/reports/profile.png";
export const DeactiveCol = [
  { key: "checkbox", header: <input type="checkbox" checked /> },
  { key: "EmployeeName", header: "Employee Name" },
  { key: "Role", header: "Role" },
  { key: "Contact", header: "Contact" },
  { key: "LastActive", header: "Last Active" },
  { key: "DeactivateReason", header: "Deactivate Reason" },
  { key: "Status", header: "Status" },
];
export const DeactiveData = [
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: "Suresh Sharma",
    Role: "Accountant",
    Contact: "9856452387",
    LastActive: "15mints ago",
    DeactivateReason: "Health Concerns",
    Status: { text: "Activate", color: "green" },
  },
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: "Suresh Sharma",
    Role: "Accountant",
    Contact: "9856452387",
    LastActive: "15mints ago",
    DeactivateReason: "Health Concerns",
    Status: { text: "Activate", color: "green" },
  },
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: "Suresh Sharma",
    Role: "Accountant",
    Contact: "9856452387",
    LastActive: "15mints ago",
    DeactivateReason: "Health Concerns",
    Status: { text: "Activate", color: "green" },
  },
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: "Suresh Sharma",
    Role: "Accountant",
    Contact: "9856452387",
    LastActive: "15mints ago",
    DeactivateReason: "Health Concerns",
    Status: { text: "Activate", color: "green" },
  },
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: "Suresh Sharma",
    Role: "Accountant",
    Contact: "9856452387",
    LastActive: "15mints ago",
    DeactivateReason: "Health Concerns",
    Status: { text: "Activate", color: "green" },
  },
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: "Suresh Sharma",
    Role: "Accountant",
    Contact: "9856452387",
    LastActive: "15mints ago",
    DeactivateReason: "Health Concerns",
    Status: { text: "Activate", color: "green" },
  },
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: "Suresh Sharma",
    Role: "Accountant",
    Contact: "9856452387",
    LastActive: "15mints ago",
    DeactivateReason: "Health Concerns",
    Status: { text: "Activate", color: "green" },
  },
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: "Suresh Sharma",
    Role: "Accountant",
    Contact: "9856452387",
    LastActive: "15mints ago",
    DeactivateReason: "Health Concerns",
    Status: { text: "Activate", color: "green" },
  },
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: "Suresh Sharma",
    Role: "Accountant",
    Contact: "9856452387",
    LastActive: "15mints ago",
    DeactivateReason: "Health Concerns",
    Status: { text: "Activate", color: "green" },
  },
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: "Suresh Sharma",
    Role: "Accountant",
    Contact: "9856452387",
    LastActive: "15mints ago",
    DeactivateReason: "Health Concerns",
    Status: { text: "Activate", color: "green" },
  },
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: "Suresh Sharma",
    Role: "Accountant",
    Contact: "9856452387",
    LastActive: "15mints ago",
    DeactivateReason: "Health Concerns",
    Status: { text: "Activate", color: "green" },
  },
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: "Suresh Sharma",
    Role: "Accountant",
    Contact: "9856452387",
    LastActive: "15mints ago",
    DeactivateReason: "Health Concerns",
    Status: { text: "Activate", color: "green" },
  },
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: "Suresh Sharma",
    Role: "Accountant",
    Contact: "9856452387",
    LastActive: "15mints ago",
    DeactivateReason: "Health Concerns",
    Status: { text: "Activate", color: "green" },
  },
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: "Suresh Sharma",
    Role: "Accountant",
    Contact: "9856452387",
    LastActive: "15mints ago",
    DeactivateReason: "Health Concerns",
    Status: { text: "Activate", color: "green" },
  },
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: "Suresh Sharma",
    Role: "Accountant",
    Contact: "9856452387",
    LastActive: "15mints ago",
    DeactivateReason: "Health Concerns",
    Status: { text: "Activate", color: "green" },
  },
];
export const ActiveCol = [
  { key: "checkbox", header: <input type="checkbox" checked /> },
  { key: "EmployeeName", header: "Employee Name" },
  { key: "Role", header: "Role" },
  { key: "Contact", header: "Contact" },
  { key: "LastActive", header: "Last Active" },
  { key: "status", header: "Status" },
  { key: "Deactivate", header: "Deactivate" },
];
export const ActiveData = [
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: "Suresh Sharma",
    Role: "Accountant",
    Contact: "9856452387",
    LastActive: "15mints ago",
    status: "Activate",
    Deactivate: { text: "Deactivate", color: "red" },
  },
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: "Suresh Sharma",
    Role: "Accountant",
    Contact: "9856452387",
    LastActive: "15mints ago",
    status: "Activate",
    Deactivate: { text: "Deactivate", color: "red" },
  },
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: "Suresh Sharma",
    Role: "Accountant",
    Contact: "9856452387",
    LastActive: "15mints ago",
    status: "Activate",
    Deactivate: { text: "Deactivate", color: "red" },
  },
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: "Suresh Sharma",
    Role: "Accountant",
    Contact: "9856452387",
    LastActive: "15mints ago",
    status: "Activate",
    Deactivate: { text: "Deactivate", color: "red" },
  },
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: "Suresh Sharma",
    Role: "Accountant",
    Contact: "9856452387",
    LastActive: "15mints ago",
    status: "Activate",
    Deactivate: { text: "Deactivate", color: "red" },
  },
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: "Suresh Sharma",
    Role: "Accountant",
    Contact: "9856452387",
    LastActive: "15mints ago",
    status: "Activate",
    Deactivate: { text: "Deactivate", color: "red" },
  },
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: "Suresh Sharma",
    Role: "Accountant",
    Contact: "9856452387",
    LastActive: "15mints ago",
    status: "Activate",
    Deactivate: { text: "Deactivate", color: "red" },
  },
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: "Suresh Sharma",
    Role: "Accountant",
    Contact: "9856452387",
    LastActive: "15mints ago",
    status: "Activate",
    Deactivate: { text: "Deactivate", color: "red" },
  },
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: "Suresh Sharma",
    Role: "Accountant",
    Contact: "9856452387",
    LastActive: "15mints ago",
    status: "Activate",
    Deactivate: { text: "Deactivate", color: "red" },
  },
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: "Suresh Sharma",
    Role: "Accountant",
    Contact: "9856452387",
    LastActive: "15mints ago",
    status: "Activate",
    Deactivate: { text: "Deactivate", color: "red" },
  },
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: "Suresh Sharma",
    Role: "Accountant",
    Contact: "9856452387",
    LastActive: "15mints ago",
    status: "Activate",
    Deactivate: { text: "Deactivate", color: "red" },
  },
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: "Suresh Sharma",
    Role: "Accountant",
    Contact: "9856452387",
    LastActive: "15mints ago",
    status: "Activate",
    Deactivate: { text: "Deactivate", color: "red" },
  },
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: "Suresh Sharma",
    Role: "Accountant",
    Contact: "9856452387",
    LastActive: "15mints ago",
    status: "Activate",
    Deactivate: { text: "Deactivate", color: "red" },
  },
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: "Suresh Sharma",
    Role: "Accountant",
    Contact: "9856452387",
    LastActive: "15mints ago",
    status: "Activate",
    Deactivate: { text: "Deactivate", color: "red" },
  },
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: "Suresh Sharma",
    Role: "Accountant",
    Contact: "9856452387",
    LastActive: "15mints ago",
    status: "Activate",
    Deactivate: { text: "Deactivate", color: "red" },
  },
];
export const AllCol = [
  { key: "checkbox", header: <input type="checkbox" checked /> },
  { key: "EmployeeName", header: "Employee Name" },
  { key: "Role", header: "Role" },
  { key: "EmailID", header: "Email ID" },
  { key: "LastActive", header: "Last Active" },
  { key: "Status", header: "Status" },
];

export const AllData = [
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: { image: profile, text: "Sumit Sharma" },
    Role: "Accountant",
    EmailID: "sureshsharma21@gmail.com",
    LastActive: "15mints ago",
    Status: {
      buttons: [{ text: "Deactivated", color: "red", id: "deactivate_1" }],
    },
  },
  {
    checkbox: <input type="checkbox" />,
    EmployeeName: { image: profile, text: "Sumit Sharma" },
    Role: "Accountant",
    EmailID: "sureshsharma21@gmail.com",
    LastActive: "15mints ago",
    Status: {
      buttons: [
        { text: "Activate", color: "green", id: "activate" },
        { text: "Deactivate", color: "red", id: "deactivate_2" },
      ],
    },
  },
];

export const employeesCols = [
  { key: "avatar", header: "Avatar" },
  { key: "firstName", header: "First Name" },
  { key: "designation", header: "Designation" },
  { key: "personalEmail", header: "Personal Email" },
  { key: "address", header: "Address" },
  { key: "Status", header: "Status" },
];
