import preview from "../../assets/companyprofile/preview.png";
export const reportCol = [
  { key: "PostID", header: "Post ID" },
  { key: "PostDate", header: "Post Date" },
  { key: "PostTime", header: "Post Time" },
  { key: "PostBy", header: "Post By" },
  { key: "ReasonOfReport", header: "Reason Of Report" },
  { key: "ViewPost", header: "View Post" },
];
export const reportData = [
  {
    PostID: "GH567654",
    PostDate: "01 May 2024",
    PostTime: "5pm",
    PostBy: "By TCS Employee",
    ReasonOfReport: "False Information..",
    ViewPost: { image: preview },
  },
  {
    PostID: "GH567654",
    PostDate: "01 May 2024",
    PostTime: "5pm",
    PostBy: "By TCS Employee",
    ReasonOfReport: "False Information..",
    ViewPost: { image: preview },
  },
  {
    PostID: "GH567654",
    PostDate: "01 May 2024",
    PostTime: "5pm",
    PostBy: "By TCS Employee",
    ReasonOfReport: "False Information..",
    ViewPost: { image: preview },
  },
  {
    PostID: "GH567654",
    PostDate: "01 May 2024",
    PostTime: "5pm",
    PostBy: "By TCS Employee",
    ReasonOfReport: "False Information..",
    ViewPost: { image: preview },
  },
  {
    PostID: "GH567654",
    PostDate: "01 May 2024",
    PostTime: "5pm",
    PostBy: "By TCS Employee",
    ReasonOfReport: "False Information..",
    ViewPost: { image: preview },
  },
  {
    PostID: "GH567654",
    PostDate: "01 May 2024",
    PostTime: "5pm",
    PostBy: "By TCS Employee",
    ReasonOfReport: "False Information..",
    ViewPost: { image: preview },
  },
  {
    PostID: "GH567654",
    PostDate: "01 May 2024",
    PostTime: "5pm",
    PostBy: "By TCS Employee",
    ReasonOfReport: "False Information..",
    ViewPost: { image: preview },
  },
  {
    PostID: "GH567654",
    PostDate: "01 May 2024",
    PostTime: "5pm",
    PostBy: "By TCS Employee",
    ReasonOfReport: "False Information..",
    ViewPost: { image: preview },
  },
  {
    PostID: "GH567654",
    PostDate: "01 May 2024",
    PostTime: "5pm",
    PostBy: "By TCS Employee",
    ReasonOfReport: "False Information..",
    ViewPost: { image: preview },
  },
  
];
